context("Simulate geno data")

load("reference_cline.Rdata")

set.seed(10)
testval <-sim_geno_cline(transect_distances = seq(0,600,20), n_ind = 40, Fis = 0,
                    decrease = F, center = 300, width = 80)
test_that("clines generated by sim_geno_cline are correct", {
  expect_equal(testval, cline)
})
